{
 "title": "Kudu-Dashboard",
 "tags": [ "kudu" ],
 "time": { "from": "now/d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "kudu_table",
    "label": "Kudu Table",
    "query": {
     "query": "label_values(kudu_on_disk_data_size, table_name)"
    }
   },
   {
    "name": "kudu_node",
    "label": "Kudu Node",
    "query": {
     "query": "label_values(kudu_on_disk_data_size{table_name=~\"$kudu_table\"}, host_ip)"
    }
   },
   {
    "name": "kudu_tablet",
    "label": "Kudu Tablet",
    "query": {
     "query": "label_values(kudu_on_disk_data_size{table_name=~\"$kudu_table\", host_ip=~\"$kudu_node\"}, partition)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Kudu Cluster", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Tablet Active",
   "type": "piechart",
   "gridPos": { "h": 11, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kudu_tablets_num_running{job=\"kudu\"}",
     "legendFormat": "{{host_ip}}"
    }
   ]
  },
  {
   "title": "Kudu Threads",
   "type": "stat",
   "gridPos": { "h": 11, "w": 5, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kudu_threads_running{job=\"kudu\"}",
     "legendFormat": "{{host_ip}}"
    }
   ]
  },
  {
   "title": "Kudu Memory",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 5, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "kudu_generic_current_allocated_bytes{job=\"kudu\"}",
     "legendFormat": "{{host_ip}}-{{id}}"
    }
   ]
  },
  {
   "title": "Kudu Write Speed",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 5, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "delta(kudu_block_manager_total_bytes_written{job=\"kudu\"}[30s]) / 30",
     "legendFormat": "{{host_ip}}-{{id}}"
    }
   ]
  },
  {
   "title": "Kudu Read Speed",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 5, "x": 19, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "delta(kudu_block_manager_total_bytes_read{job=\"kudu\"}[30s]) / 30",
     "legendFormat": "{{host_ip}}-{{id}}"
    }
   ]
  },
  {
   "title": "Kudu Table",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "sum(kudu_rows_deleted{job=\"kudu\"}) by (table_name)",
     "legendFormat": "rows_deleted"
    },
    {
     "expr": "sum(kudu_rows_inserted{job=\"kudu\"}) by (table_name)",
     "legendFormat": "rows_inserted"
    },
    {
     "expr": "sum(kudu_rows_updated{job=\"kudu\"}) by (table_name)",
     "legendFormat": "rows_updated"
    },
    {
     "expr": "sum(kudu_rows_upserted{job=\"kudu\"}) by (table_name)",
     "legendFormat": "rows_upserted"
    },
    {
     "expr": "sum(kudu_live_row_count{type=\"table\", job=\"kudu\"}) by (table_name)"
    },
    {
     "expr": "sum(round(delta(kudu_live_row_count{type=\"table\", job=\"kudu\"}[30s]) / 30)) by (table_name)"
    },
    {
     "expr": "count(kudu_on_disk_data_size{type=\"tablet\", job=\"kudu\"}) by (table_name)"
    },
    {
     "expr": "sum(kudu_on_disk_data_size{type=\"tablet\",job=\"kudu\"}) by (table_name)"
    },
    {
     "expr": "sum(round(delta(kudu_live_row_count{type=\"table\", job=\"kudu\"} [${__range_s}s]))) by (table_name)"
    },
    {
     "expr": "sum(round(delta(kudu_live_row_count{type=\"table\", job=\"kudu\"} [${__range_s}s])) / \nround(kudu_live_row_count{type=\"table\", job=\"kudu\"} offset ${__range_s}s + 1)) by (table_name)"
    }
   ]
  },
  { "title": "Kudu Table", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Tablet",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 5, "x": 0, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kudu_on_disk_data_size{table_name=~\"$kudu_table\", host_ip=~\"$kudu_node\", type=\"tablet\", job=\"kudu\"}) by (host_ip)",
     "legendFormat": "{{host_ip}}"
    }
   ]
  },
  {
   "title": "Writing Speed",
   "type": "stat",
   "gridPos": { "h": 5, "w": 7, "x": 5, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "floor(\nsum(delta(kudu_rows_upserted{table_name=~\"$kudu_table\", host_ip=~\"$kudu_node\", job=\"kudu\"}[30s])/30) by (host_ip) + \nsum(delta(kudu_rows_inserted{table_name=~\"$kudu_table\", host_ip=~\"$kudu_node\", job=\"kudu\"}[30s])/30) by (host_ip) + \nsum(delta(kudu_rows_updated{table_name=~\"$kudu_table\", host_ip=~\"$kudu_node\", job=\"kudu\"}[30s])/30) by (host_ip) + \nsum(delta(kudu_rows_deleted{table_name=~\"$kudu_table\", host_ip=~\"$kudu_node\", job=\"kudu\"}[30s])/30) by (host_ip)\n)",
     "legendFormat": "{{host_ip}}"
    }
   ]
  },
  {
   "title": "Total Writing Speed",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "floor(\nsum(delta(kudu_rows_upserted{table_name=~\"$kudu_table\", host_ip=~\"$kudu_node\", job=\"kudu\"}[30s])/30) by (table_name) + \nsum(delta(kudu_rows_inserted{table_name=~\"$kudu_table\", host_ip=~\"$kudu_node\", job=\"kudu\"}[30s])/30) by (table_name) + \nsum(delta(kudu_rows_updated{table_name=~\"$kudu_table\", host_ip=~\"$kudu_node\", job=\"kudu\"}[30s])/30) by (table_name) + \nsum(delta(kudu_rows_deleted{table_name=~\"$kudu_table\", host_ip=~\"$kudu_node\", job=\"kudu\"}[30s])/30) by (table_name)\n)",
     "legendFormat": "{{table_name}}"
    }
   ]
  },
  {
   "title": "Kudu Table Writing Speed",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 10, "x": 14, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "floor(\nsum(delta(kudu_rows_upserted{table_name=~\"$kudu_table\", host_ip=~\"$kudu_node\", job=\"kudu\"}[30s])/30) by (table_name) + \nsum(delta(kudu_rows_inserted{table_name=~\"$kudu_table\", host_ip=~\"$kudu_node\", job=\"kudu\"}[30s])/30) by (table_name) + \nsum(delta(kudu_rows_updated{table_name=~\"$kudu_table\", host_ip=~\"$kudu_node\", job=\"kudu\"}[30s])/30) by (table_name) + \nsum(delta(kudu_rows_deleted{table_name=~\"$kudu_table\", host_ip=~\"$kudu_node\", job=\"kudu\"}[30s])/30) by (table_name)\n)",
     "legendFormat": "{{table_name}} Total Speed"
    },
    {
     "expr": "round(\nsum(delta(kudu_rows_upserted{table_name=~\"$kudu_table\", host_ip=~\"$kudu_node\", job=\"kudu\"}[30s])/30) by (table_name)\n)",
     "legendFormat": "{{table_name}} Upsert Speed"
    },
    {
     "expr": "round(\nsum(delta(kudu_rows_inserted{table_name=~\"$kudu_table\", host_ip=~\"$kudu_node\", job=\"kudu\"}[30s])/30) by (table_name)\n)",
     "legendFormat": "{{table_name}} Insert Speed"
    },
    {
     "expr": "round(\nsum(delta(kudu_rows_updated{table_name=~\"$kudu_table\", host_ip=~\"$kudu_node\", job=\"kudu\"}[30s])/30) by (table_name)\n)",
     "legendFormat": "{{table_name}} Update Speed"
    },
    {
     "expr": "round(\nsum(delta(kudu_rows_deleted{table_name=~\"$kudu_table\", host_ip=~\"$kudu_node\", job=\"kudu\"}[30s])/30) by (table_name)\n)",
     "legendFormat": "{{table_name}} Delete Speed"
    }
   ]
  },
  {
   "title": "Disk",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 7, "x": 5, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kudu_on_disk_data_size{table_name=~\"$kudu_table\", host_ip=~\"$kudu_node\", partition=~\"$kudu_tablet\", type=\"tablet\", job=\"kudu\"}) by (host_ip)",
     "legendFormat": "{{host_ip}}"
    }
   ]
  },
  {
   "title": "Table Size",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kudu_on_disk_data_size{table_name=~\"$kudu_table\", host_ip=~\"$kudu_node\", partition=~\"$kudu_tablet\", type=\"tablet\", job=\"kudu\"}) by (table_name)",
     "legendFormat": "{{table_name}}"
    }
   ]
  },
  {
   "title": "Status",
   "type": "table",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 35 },
   "targets": [
    {
     "expr": "round(\ndelta(kudu_rows_upserted{table_name=~\"$kudu_table\", host_ip=~\"$kudu_node\", partition=~\"$kudu_tablet\", job=\"kudu\"}[30s]) / 30\n)"
    },
    {
     "expr": "round(\ndelta(kudu_rows_inserted{table_name=~\"$kudu_table\", host_ip=~\"$kudu_node\", partition=~\"$kudu_tablet\", job=\"kudu\"}[30s]) / 30\n)"
    },
    {
     "expr": "round(\ndelta(kudu_rows_deleted{table_name=~\"$kudu_table\", host_ip=~\"$kudu_node\", partition=~\"$kudu_tablet\", job=\"kudu\"}[30s]) / 30\n)"
    },
    {
     "expr": "round(\ndelta(kudu_rows_updated{table_name=~\"$kudu_table\", host_ip=~\"$kudu_node\", partition=~\"$kudu_tablet\", job=\"kudu\"}[30s]) / 30\n)"
    },
    {
     "expr": "round(\ndelta(kudu_rows_upserted{table_name=~\"$kudu_table\", host_ip=~\"$kudu_node\", partition=~\"$kudu_tablet\", job=\"kudu\"}[30s]) / 30 +\ndelta(kudu_rows_inserted{table_name=~\"$kudu_table\", host_ip=~\"$kudu_node\", partition=~\"$kudu_tablet\", job=\"kudu\"}[30s]) / 30 +\ndelta(kudu_rows_deleted{table_name=~\"$kudu_table\", host_ip=~\"$kudu_node\", partition=~\"$kudu_tablet\", job=\"kudu\"}[30s]) / 30 +\ndelta(kudu_rows_updated{table_name=~\"$kudu_table\", host_ip=~\"$kudu_node\", partition=~\"$kudu_tablet\", job=\"kudu\"}[30s]) / 30\n)"
    }
   ]
  }
 ]
}